apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-backups
  labels:
    app: mongodb-backups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-backups
  template:
    metadata:
      labels:
        app: mongodb-backups
    spec:
      containers:
        - name: mongodb-backups
          image: neo9sas/mongodb-backups:$RELEASE_VERSION
          command:
            - /bin/mongodb-backups
            - --config
            - /etc/config/config.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
              cpu: 10m
      volumes:
        - name: config-volume
          configMap:
            name: mongodb-backups

