apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-backups
  name: mongodb-backups
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mongodb-backups

